### ISSUE TITLE
python-debian dependency

### ISSUE THREAD

**Issue by pombredanne** [sassoftware/python-debpkgr#1]
I noted that the python-debian dep is not listed in the setup.py requirements.
As a heads-up, note that I am working with the python-debian authors to relicense it under a library-friendly license. I will keep you posted as this progresses. It takes some time to contact all authors.

**Comment by mibanescu** [comment]
It is, indirectly. We are using pbr, which reads requirements.txt, where you can see:

python-debian~=0.1.28

Did you try it and it didn't work for you, or you were just expecting a value there and didn't see it?

Thank you for letting us know about python-debian.

**Comment by pombredanne** [comment]
@mibanescu I did not try. I just thought pbr only used setup.cfg. So you are good.
