### ISSUE TITLE
Create InRelease files

### ISSUE THREAD

**Issue by qha** [sassoftware/python-debpkgr#14]
As i understand it this package is responsible for creating repository metadata in [pulp_deb](https://github.com/pulp/pulp_deb).

It seems there is no support for creating the InRelease file in debpkgr.aptrepo and according to my testing on Ubuntu 18 lts and the [Debian wiki](https://wiki.debian.org/DebianRepository/Format#A.22Release.22_files) the InRelease file is required by current apt clients.

According to the same wiki article the InRelease file is the same as the Release file but with a clearsign signature instead of the detached signature of the Release file.

**Comment by mibanescu** [comment]
Apologies for not noticing this issue.

Please have a look at the README.rst file. There is documentation on how to set up signing, with a suggested script. You can change that script to add another gpg command that generates an InRelease file (result of --output) and change --detach-sign to --clearsign. I have not tested this, but I see no reason it won't work.

Please reopen if that's not satisfactory.
